from helper import *

ATTACK_MODIFIER = 10
PROTECTION_MODIFIER = 30
GATHER_MODIFIER = 60
GATHERSPEED_MODIFIER = 30
CAPACITE_MODIFIER = 30
DEFENCE_MODIFIER = 15
HEALTH_MODIFIER = 15
WEIGHT_FACTOR = 100
COST_ADJUSTEMENT = 1000
